
server:
  port: 8888 # સર્વર પોર્ટ 8888 પર ચાલશે

spring:
  application:
    name: config-server # સર્વિસનું નામ
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dodiamahesh/lms-config-repo.git
          default-label: master
          username: dodiamahesh
          password: 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
          search-paths: # રિપોઝીટરીમાં રૂપરેખાંકન ફાઇલો ક્યાં શોધવી
            - configurations


